### 1. Getting Telegram API creadentials

1. Go to Telegram API website **https://my.telegram.org/apps**
2. **Login** with your Telegram phone number
3. **Create new application:**
   - App title: `My Telegram Parser` (any name)
   - Short name: `parser` (any short name)  
   - Platform: `Desktop`
4. **Copy your credentials:**
   - API ID (numbers): `1234567`
   - API Hash (string): `abc123def456...`
5. Create a file named `.env` in your project folder with your credentials:
   
   TG_API_ID=`1234567` (should be integer, not a string!)  
   TG_API_HASH=`abc123def456...`

### 2. Installation

In [1]:
# Installing required packages
%pip install -r requirements.txt
%pip install pandas #not required, only for testing

Requirement already satisfied: Pyrogram in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (2.0.106)
Requirement already satisfied: python-dotenv in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (1.1.1)
Requirement already satisfied: tgcrypto in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (1.2.5)
Requirement already satisfied: pyaes==1.6.1 in ./.venv/lib/python3.12/site-packages (from Pyrogram->-r requirements.txt (line 1)) (1.6.1)
Requirement already satisfied: pysocks==1.7.1 in ./.venv/lib/python3.12/site-packages (from Pyrogram->-r requirements.txt (line 1)) (1.7.1)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in ./.venv/lib/python3.12/site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.12/site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Importing the parser class
from tg_api_data_parser import TgApiParser

### 3. Finding the chats and channels ids

#### Method 1: Using Telegram Bots

1. **For any chat**: Forward a message from the target chat to **@userinfobot**
  - It will reply with chat information including the ID

2. **For channels you admin**: Add **@raw_data_bot** to your channel
  - Send any message, and it will show the channel ID

#### Method 2: Using Telegram web interface


1. **Login into web interface**
  - Login to **https://web.telegram.org**
  - Click on the chat or channel you want to parse
  - Look at the URL in your browser address bar

2. **Extract the ID from URL:**
  - For **public channels/groups**: URL shows `https://web.telegram.org/k/#@channel_username`
    - Use: `"@channel_username"` (include the @ symbol)
  - For **personal chats**: URL shows `https://web.telegram.org/k/#1234567890`
    - Use: `1234567890` (positive number)
  - **private chats/groups** are currently not avaliable for downloads

### 4. Parcing API data

In [8]:
# Replace with your own chat_id
chat_id = '@besedernedaber'

In [9]:
# Initializing the parser.
parser = TgApiParser(chat_id=chat_id)

In [ ]:
# Loading data from the specified chat with a limit on the number of messages.

# The first time you launch this line you will be asked
# to enter your phone number used for Telegram registation,
# and then to enter the code sent to you via Telegram.
# After that, the data will be loaded and saved to a file.

await parser.load_data()

[my_session] Waiting for 23 seconds before continuing (required by "messages.GetHistory")
[my_session] Waiting for 24 seconds before continuing (required by "messages.GetHistory")
[my_session] Waiting for 22 seconds before continuing (required by "messages.GetHistory")
[my_session] Waiting for 22 seconds before continuing (required by "messages.GetHistory")
[my_session] Waiting for 22 seconds before continuing (required by "messages.GetHistory")
[my_session] Waiting for 24 seconds before continuing (required by "messages.GetHistory")

In [11]:
# Parsing the data received by API
parser.extract_messages()

In [ ]:
# Load media files (photos, videos, documents, voice messages, audio files to a folder)

await parser.get_files()

In [8]:
# Save the parsed messages to a CSV file(s) for further analysis
parser.save_chat(save_actions=True)

### 5. Use cases

In [10]:
import pandas as pd

In [ ]:
# Extract the parsed content messages from the parser
# (messages from the users, not system messages)
content_messages = parser.content_messages

# Convert the list of message dictionaries to a pandas DataFrame for analysis
content_messages_table = pd.DataFrame(content_messages)

# Display the first 10 rows to inspect the data structure and content
content_messages_table.head(10)

,msg_id,posting_time,edited,reply_to_msg_id,views,reactions,sender,sender_id,sender_name,forward_from,forward_id,forward_name,media_type,file_id,content,file_name,chat_id,chat_name,file
0,12364,2025-05-22 12:11:17,NaT,12363.0,NaN,None,user,1070967505,None,None,NaN,None,text,None,Шел 3030 год.......,None,-1001582532081,"Чатик канала ""Первый Дан""",None
1,12365,2025-05-22 15:15:12,2025-05-22 15:16:57,NaN,2942.0,"{\n ""_"": ""MessageReactions"",\n ""reaction...",group,-1001163672230,Первый Дан | Израиль | Новости | Мнения,chat,-1.001164e+12,Первый Дан | Израиль | Новости | Мнения,photo,AgACAgIAAx0CXlOF8QACME1orqKXhz7-68zE1gtT2FFvQP...,"“Обещаю, что следующий эпизод мы запишем о чем...",None,-1001582532081,"Чатик канала ""Первый Дан""",Chat_-1001582532081/files/photo_2025-05-22_15-...
2,12366,2025-05-22 15:35:27,2025-05-22 15:36:40,NaN,4213.0,"{\n ""_"": ""MessageReactions"",\n ""reaction...",group,-1001163672230,Первый Дан | Израиль | Новости | Мнения,chat,-1.002352e+12,Диана Тосунян,text,None,None,None,-1001582532081,"Чатик канала ""Первый Дан""",None
3,12367,2025-05-22 15:48:13,2025-05-22 15:49:26,12366.0,NaN,"{\n ""_"": ""MessageReactions"",\n ""reaction...",user,44674721,sshoff,None,NaN,None,text,None,"Я только за, если все ""политики"" организации Х...",None,-1001582532081,"Чатик канала ""Первый Дан""",None
4,12368,2025-05-22 17:23:53,2025-05-22 17:27:49,NaN,1186.0,"{\n ""_"": ""MessageReactions"",\n ""reaction...",group,-1001163672230,Первый Дан | Израиль | Новости | Мнения,chat,-1.001164e+12,Первый Дан | Израиль | Новости | Мнения,video,BAACAgIAAx0CXlOF8QACMFBorqKXc-reddhQn-4LYOcstb...,Юваль Рафаэль и Керен Пелес исполнили песню Ne...,IMG_1891.MP4,-1001582532081,"Чатик канала ""Первый Дан""",Chat_-1001582532081/files/IMG_1891.MP4
5,12369,2025-05-22 17:42:53,NaT,12368.0,NaN,None,user,294091036,Arokh07,None,NaN,None,text,None,"Вот радовались победе Юваль, а спросите себя :...",None,-1001582532081,"Чатик канала ""Первый Дан""",None
6,12370,2025-05-22 18:32:22,2025-05-22 18:36:10,NaN,1409.0,"{\n ""_"": ""MessageReactions"",\n ""reaction...",group,-1001163672230,Первый Дан | Израиль | Новости | Мнения,chat,-1.001164e+12,Первый Дан | Израиль | Новости | Мнения,text,None,Накануне БАГАЦ признал решение правительства у...,None,-1001582532081,"Чатик канала ""Первый Дан""",None
7,12371,2025-05-22 18:37:49,2025-05-22 18:39:36,NaN,1876.0,"{\n ""_"": ""MessageReactions"",\n ""reaction...",group,-1001163672230,Первый Дан | Израиль | Новости | Мнения,chat,-1.001164e+12,Первый Дан | Израиль | Новости | Мнения,text,None,"США проинформировали Израиль, что продолжат пр...",None,-1001582532081,"Чатик канала ""Первый Дан""",None
8,12372,2025-05-23 17:18:27,2025-05-23 17:29:11,NaN,1566.0,None,group,-1001163672230,Первый Дан | Израиль | Новости | Мнения,chat,-1.001164e+12,Первый Дан | Израиль | Новости | Мнения,text,None,None,None,-1001582532081,"Чатик канала ""Первый Дан""",None
9,12373,2025-05-23 17:28:33,2025-05-23 17:57:38,12372.0,NaN,"{\n ""_"": ""MessageReactions"",\n ""reaction...",user,361128129,Polarlightwolf,None,NaN,None,text,None,За выживание подсудимого на посту.,None,-1001582532081,"Чатик канала ""Первый Дан""",None

In [12]:
# What are the most reposted channels?

content_messages_table.loc[content_messages_table['forward_from'] == 'chat', 'forward_name'].value_counts()

forward_name
Первый Дан | Израиль | Новости | Мнения                                                                                             828
Израиль. Коротко о главном                                                                                                           33
ИЗРАИЛЬ 🇮🇱 НАШ | СЕВЕР                                                                                                                7
Коля Хадашот                                                                                                                          6
Восточный Синдром                                                                                                                     3
Дмитрий Дубов                                                                                                                         3
Нашел билеты из 🇮🇱                                                                                                                    3
ParaBellum (by Ilya Bezruchko - איליה בזרוצ׳קו)                                                                                       2
Диана Тосунян                                                                                                                         2
Пресс-секретарь ЦАХАЛа - Анна Уколова                                                                                                 2
Про Олимов и Людей                                                                                                                    2
Точка встречи                                                                                                                         2
Ближний В. (мои 5 агорот)                                                                                                             2
Kehilat Daniel Jaffa 🍊                                                                                                                2
НАХОН                                                                                                                                 2
Аппельберг                                                                                                                            1
Ялла, Балаган!                                                                                                                        1
Бухта Левиафана 🐋                                                                                                                     1
Дежурный по Израилю                                                                                                                   1
Кушнир на проводе                                                                                                                     1
Война с Ордой. Сергей Ауслендер                                                                                                       1
🎯 Другое мнение. Элина Бардач-Ялова о главных событиях Израиля                                                                        1
מיכאל שמש                                                                                                                             1
Израиль по-русски                                                                                                                     1
Dmitri Gendelman                                                                                                                      1
Война и мир на Ближнем Востоке- Дина Лиснянская.                                                                                      1
Обзиратель. Война на Ближнем Востоке ⚔️                                                                                               1
✈️ Израильский Авиа-Гид – Полёты за границу                                                                                           1
SOTA                                                                                                                                  1
Ульпан.Политика | Израиль | Новости | Интервью | Аналитика | Спорт | Война | Обстрелы | Ближний Восток | Газа | Простыми словами      1
Name: count, dtype: int64

In [13]:
#  Get non- text media messages with links to stored files 
content_messages_table.loc[content_messages_table.file.notna(), ['msg_id', 'posting_time', 'media_type', 'content', 'file_name', 'file']]

,msg_id,posting_time,media_type,content,file_name,file
1,12365,2025-05-22 15:15:12,photo,"“Обещаю, что следующий эпизод мы запишем о чем...",None,Chat_-1001582532081/files/photo_2025-05-22_15-...
4,12368,2025-05-22 17:23:53,video,Юваль Рафаэль и Керен Пелес исполнили песню Ne...,IMG_1891.MP4,Chat_-1001582532081/files/IMG_1891.MP4
15,12379,2025-05-25 16:06:15,photo,Еще 2 заложника встретили дни рождения в плену...,None,Chat_-1001582532081/files/photo_2025-05-25_15-...
16,12380,2025-05-25 16:06:15,photo,None,None,Chat_-1001582532081/files/photo_2025-05-25_15-...
21,12386,2025-05-26 08:39:56,photo,Утром Дня Иерусалима в столице проходит «Парад...,None,Chat_-1001582532081/files/photo_2025-05-26_08-...
...,...,...,...,...,...,...
1984,14374,2025-08-26 17:31:15,photo,Две главных фотографии вечера из двух городов.,None,Chat_-1001582532081/files/photo_2025-08-26_17-...
1985,14375,2025-08-26 17:31:15,photo,None,None,Chat_-1001582532081/files/photo_2025-08-26_17-...
1987,14377,2025-08-26 20:23:20,video,"Кстати, нашумевший концерт певца в стиле мизра...",IMG_1481.MP4,Chat_-1001582532081/files/IMG_1481.MP4
1989,14379,2025-08-26 20:37:09,photo,Книга Синвара распространяется в рф с одобрени...,None,Chat_-1001582532081/files/photo_2025-08-26_17-...
1993,14383,2025-08-26 21:03:06,video,Премьер министр Израиля Биньямин Нетаниягу дал...,IMG_1482.MP4,Chat_-1001582532081/files/IMG_1482.MP4